/*
 * ELockPool.hh
 *
 *  Created on: 2014-6-4
 *      Author: cxxjava@163.com
 */

#ifndef ELOCKPOOL_HH_
#define ELOCKPOOL_HH_

//@see: sofa-pbrpc-master/src/sofa/pbrpc/smart_ptr/detail/spinlock_pool.hpp

#include "ESpinLock.hh"
#include "EReentrantLock.hh"

namespace efc {

#define POLLSIZE 41

//use spin lock

#define SSYNCBLOCKFOR(i, p) SYNCBLOCK(ESpinLockPool<i>::lockFor(p))

#define SCOPED_SLOCK0(p) SSYNCBLOCKFOR(0, p) //0 for sp!!!

#define SCOPED_SLOCK1(p) SSYNCBLOCKFOR(1, p) //1 for ?
#define SCOPED_SLOCK2(p) SSYNCBLOCKFOR(2, p) //2 for ?
#define SCOPED_SLOCK3(p) SSYNCBLOCKFOR(3, p) //3 for ?
#define SCOPED_SLOCK4(p) SSYNCBLOCKFOR(4, p) //4 for ?
#define SCOPED_SLOCK5(p) SSYNCBLOCKFOR(5, p) //5 for ?

template< int I > class ESpinLockPool
{
private:
    static ELock* pool_[POLLSIZE];

public:
    static ELock* lockFor(void const* pv)
    {
    	es_size_t i = reinterpret_cast<es_size_t>(pv) % POLLSIZE;
        return pool_[i];
    }
};

#define ES_SPINLOCK_INIT new ESpinLock()

template< int I > ELock* ESpinLockPool< I >::pool_[POLLSIZE] =
{
	ES_SPINLOCK_INIT, ES_SPINLOCK_INIT, ES_SPINLOCK_INIT, ES_SPINLOCK_INIT, ES_SPINLOCK_INIT,
	ES_SPINLOCK_INIT, ES_SPINLOCK_INIT, ES_SPINLOCK_INIT, ES_SPINLOCK_INIT, ES_SPINLOCK_INIT,
	ES_SPINLOCK_INIT, ES_SPINLOCK_INIT, ES_SPINLOCK_INIT, ES_SPINLOCK_INIT, ES_SPINLOCK_INIT,
	ES_SPINLOCK_INIT, ES_SPINLOCK_INIT, ES_SPINLOCK_INIT, ES_SPINLOCK_INIT, ES_SPINLOCK_INIT,
	ES_SPINLOCK_INIT, ES_SPINLOCK_INIT, ES_SPINLOCK_INIT, ES_SPINLOCK_INIT, ES_SPINLOCK_INIT,
	ES_SPINLOCK_INIT, ES_SPINLOCK_INIT, ES_SPINLOCK_INIT, ES_SPINLOCK_INIT, ES_SPINLOCK_INIT,
	ES_SPINLOCK_INIT, ES_SPINLOCK_INIT, ES_SPINLOCK_INIT, ES_SPINLOCK_INIT, ES_SPINLOCK_INIT,
	ES_SPINLOCK_INIT, ES_SPINLOCK_INIT, ES_SPINLOCK_INIT, ES_SPINLOCK_INIT, ES_SPINLOCK_INIT,
	ES_SPINLOCK_INIT
};

//=============================================================================

//use reentrant lock

#define RSYNCBLOCKFOR(i, p) SYNCBLOCK(EReentrantLockPool<i>::lockFor(p))

#define SCOPED_RLOCK0(p) RSYNCBLOCKFOR(0, p) //0 for sp!!!

#define SCOPED_RLOCK1(p) RSYNCBLOCKFOR(1, p) //1 for ?
#define SCOPED_RLOCK2(p) RSYNCBLOCKFOR(2, p) //2 for ?
#define SCOPED_RLOCK3(p) RSYNCBLOCKFOR(3, p) //3 for ?
#define SCOPED_RLOCK4(p) RSYNCBLOCKFOR(4, p) //4 for ?
#define SCOPED_RLOCK5(p) RSYNCBLOCKFOR(5, p) //5 for ?

template< int I > class EReentrantLockPool
{
private:
    static ELock* pool_[POLLSIZE];

public:
    static ELock* lockFor(void const* pv)
    {
    	es_size_t i = reinterpret_cast<es_size_t>(pv) % POLLSIZE;
        return pool_[i];
    }
};

#define ES_REENTRANTLOCK_INIT new EReentrantLock()

template< int I > ELock* EReentrantLockPool< I >::pool_[POLLSIZE] =
{
	ES_REENTRANTLOCK_INIT, ES_REENTRANTLOCK_INIT, ES_REENTRANTLOCK_INIT, ES_REENTRANTLOCK_INIT, ES_REENTRANTLOCK_INIT,
	ES_REENTRANTLOCK_INIT, ES_REENTRANTLOCK_INIT, ES_REENTRANTLOCK_INIT, ES_REENTRANTLOCK_INIT, ES_REENTRANTLOCK_INIT,
	ES_REENTRANTLOCK_INIT, ES_REENTRANTLOCK_INIT, ES_REENTRANTLOCK_INIT, ES_REENTRANTLOCK_INIT, ES_REENTRANTLOCK_INIT,
	ES_REENTRANTLOCK_INIT, ES_REENTRANTLOCK_INIT, ES_REENTRANTLOCK_INIT, ES_REENTRANTLOCK_INIT, ES_REENTRANTLOCK_INIT,
	ES_REENTRANTLOCK_INIT, ES_REENTRANTLOCK_INIT, ES_REENTRANTLOCK_INIT, ES_REENTRANTLOCK_INIT, ES_REENTRANTLOCK_INIT,
	ES_REENTRANTLOCK_INIT, ES_REENTRANTLOCK_INIT, ES_REENTRANTLOCK_INIT, ES_REENTRANTLOCK_INIT, ES_REENTRANTLOCK_INIT,
	ES_REENTRANTLOCK_INIT, ES_REENTRANTLOCK_INIT, ES_REENTRANTLOCK_INIT, ES_REENTRANTLOCK_INIT, ES_REENTRANTLOCK_INIT,
	ES_REENTRANTLOCK_INIT, ES_REENTRANTLOCK_INIT, ES_REENTRANTLOCK_INIT, ES_REENTRANTLOCK_INIT, ES_REENTRANTLOCK_INIT,
	ES_REENTRANTLOCK_INIT
};

} // namespace efc

#endif /* ELOCKPOOL_HH_ */
